spring:
  application:
    name: web-ban-hang-gia-dinh
  
  # Database Configuration - H2 for demo
  datasource:
    url: jdbc:h2:mem:webbanhanggiadinh
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:ThisIsAVeryLongSecretKeyForJWTSigningThatIsAtLeast512BitsLongForHS512AlgorithmToWorkProperly}
    expiration: 86400000 # 24 hours
  expiration: 86400000 # 24 hours

# File Storage
file:
  upload-dir: ${UPLOAD_DIR:./uploads}

server:
  port: 8080

# Logging
logging:
  level:
    com.giadinh.banphutung: DEBUG
